// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEcpngWaAeMuYo8uGNT0-FGJygYSsoeCo',
    appId: '1:184493057689:web:54bf90fb644059b92aba08',
    messagingSenderId: '184493057689',
    projectId: 'test1-6438f',
    authDomain: 'test1-6438f.firebaseapp.com',
    storageBucket: 'test1-6438f.firebasestorage.app',
    measurementId: 'G-GN8S68471L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67quBmvMsFb20FwiGRXQWt_eMmiNTcCg',
    appId: '1:184493057689:android:ea3c8cfebe99dd102aba08',
    messagingSenderId: '184493057689',
    projectId: 'test1-6438f',
    storageBucket: 'test1-6438f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyVeXOJX8u1p-STFn3r0ha0ddBD4FJ2KA',
    appId: '1:184493057689:ios:b33e0706e79ef4952aba08',
    messagingSenderId: '184493057689',
    projectId: 'test1-6438f',
    storageBucket: 'test1-6438f.firebasestorage.app',
    iosBundleId: 'Test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyVeXOJX8u1p-STFn3r0ha0ddBD4FJ2KA',
    appId: '1:184493057689:ios:b33e0706e79ef4952aba08',
    messagingSenderId: '184493057689',
    projectId: 'test1-6438f',
    storageBucket: 'test1-6438f.firebasestorage.app',
    iosBundleId: 'Test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEcpngWaAeMuYo8uGNT0-FGJygYSsoeCo',
    appId: '1:184493057689:web:3ffa10ea8745a0482aba08',
    messagingSenderId: '184493057689',
    projectId: 'test1-6438f',
    authDomain: 'test1-6438f.firebaseapp.com',
    storageBucket: 'test1-6438f.firebasestorage.app',
    measurementId: 'G-2CZ6V7B9DF',
  );
}
